language: php
 
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
 
install:
  - composer self-update
  - composer require satooshi/php-coveralls:~0.6@stable
  - composer install --prefer-source --no-interaction
 
script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 src tests
  - if [[ ! $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then ./vendor/bin/test-reporter; fi

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    on_success: always
    on_failure: always
